name    'dbox-jobsub_server'
version '0.0.1'
source 'built with selected files from old GCOS puppetrepo-jobsub and a tutorial at https://www.digitalocean.com/community/tutorials/how-to-create-a-puppet-module-to-automate-wordpress-installation-on-ubuntu-14-04 '
author 'Dennis D. Box, dbox@fnal.gov'
license 'Apache License, Version 2.0'
summary 'install and configure a jobsub server in a hurry'
description 'Install and configure a jobsub server in a Hurry. Configuration is variables in manifest/vars.pp'
project_page 'https://cdcvs.fnal.gov/redmine/projects/jobsub/wiki'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
